name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test_project:
    name: ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: macOS
            os: macOS-latest
          - build: Windows
            os: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.65.0
          profile: minimal
          components: clippy
      - name: Build project
        run: cargo build --release --locked --lib
      - name: Test project
        run: cargo test --locked
      - name: Clippy project
        run: cargo clippy --all-targets -- -D warnings 


